import type { Metadata } from 'next'
import { Inter, Saira } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/website/Navbar';
import { Suspense } from 'react';

const inter = Inter({ subsets: ['latin'] })
const saira = Saira({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'BD Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-neutral-50 text-black selection:bg-teal-300 dark:bg-neutral-900 dark:text-white dark:selection:bg-pink-500 dark:selection:text-white">
        <NavBar />
        <Suspense>
          <main>{children}</main>
        </Suspense>
      </body>
    </html>
  )
}
